Add code coverage badge
FaustXVI/junit5-docker pull request #77
Opened 2016-12-21 09:29 UTC by zeroual

2016-12-21 13:27 UTC, vdemeester commented on README.md
> +[![codecov](https://codecov.io/gh/zeroual/junit5-docker/branch/master/graph/badge.svg)](https://codecov.io/gh/zeroual/junit5-docker)
You will have to use `FaustXVI` url here :angel:

2016-12-21 13:54 UTC, zeroual commented on README.md
> +[![codecov](https://codecov.io/gh/zeroual/junit5-docker/branch/master/graph/badge.svg)](https://codecov.io/gh/zeroual/junit5-docker)
yeap , i asked @FaustXVI  to create an account and give me the new url

2016-12-21 22:22 UTC, FaustXVI requested changes

2016-12-21 22:22 UTC, FaustXVI commented on README.md
> +[![codecov](https://codecov.io/gh/zeroual/junit5-docker/branch/master/graph/badge.svg)](https://codecov.io/gh/zeroual/junit5-docker)
https://codecov.io/gh/FaustXVI/junit5-docker here it is :)

2016-12-21 22:30 UTC, FaustXVI commented on .travis.yml
> +    - bash <(curl -s https://codecov.io/bash)
mvn jacoco:report will be needed too :)

2016-12-28 11:05 UTC, vdemeester commented
ping @zeroual

2017-02-25 16:08 UTC, FaustXVI commented
@zeroual should we close the PR?

2017-02-26 14:46 UTC, closed without merging